data:extend({
   {
      type = "int-setting",
      name = "trainstop-penalty",
      setting_type = "startup",
      default_value = 2000,
      minimum_value = 1,
      maximum_value = 60000,
   },
   {
      type = "int-setting",
      name = "manual-withplayer-penalty",
      setting_type = "startup",
      default_value = 2000,
      minimum_value = 1,
      maximum_value = 60000,
   },
   {
      type = "int-setting",
      name = "manual-noplayer-penalty",
      setting_type = "startup",
      default_value = 7000,
      minimum_value = 1,
      maximum_value = 60000,
   },   
   {
      type = "int-setting",
      name = "circuit-penalty",
      setting_type = "startup",
      default_value = 1000,
      minimum_value = 1,
      maximum_value = 60000,
   },   
   {
      type = "int-setting",
      name = "train-waitstation-penalty",
      setting_type = "startup",
      default_value = 500,
      minimum_value = 1,
      maximum_value = 60000,
   },
   {
      type = "int-setting",
      name = "train-waitstation-nostops-penalty",
      setting_type = "startup",
      default_value = 1000,
      minimum_value = 1,
      maximum_value = 60000,
   },
   {
      type = "int-setting",
      name = "arriving-stop-penalty",
      setting_type = "startup",
      default_value = 100,
      minimum_value = 1,
      maximum_value = 60000,
   },
   {
      type = "int-setting",
      name = "arriving-signal-penalty",
      setting_type = "startup",
      default_value = 100,
      minimum_value = 1,
      maximum_value = 60000,
   },   
   {
      type = "int-setting",
      name = "waiting-signal-penalty",
      setting_type = "startup",
      default_value = 100,
      minimum_value = 1,
      maximum_value = 60000,
   },   
   {
      type = "double-setting",
      name = "waiting-at-signal-multiplier",
      setting_type = "startup",
      default_value = 0.1,
      minimum_value = 0.001,
      maximum_value = 100,
	}
})
